[project]
name = "localllm"
version = "0.1.0"
description = "Personal project where I experiment with LLMs locally"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ollama>=0.6.1",
]
